---
abstract: 'display tail to your browser'
author:
  - 'hayajo <hayajo@cpan.org>'
build_requires:
  Test::More: '0.88'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v1.0.0, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Webtail
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Mojolicious::Plugin::Webtail:
    file: lib/Mojolicious/Plugin/Webtail.pm
    version: '0.06'
requires:
  Mojolicious: '3.02'
  Text::ParseWords: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/hayajo/Mojolicious-Plugin-Webtail/issues
  homepage: https://github.com/hayajo/Mojolicious-Plugin-Webtail
  repository: git://github.com/hayajo/Mojolicious-Plugin-Webtail.git
version: '0.06'
x_contributors:
  - 'hayajo <hayato.imai@gmail.com>'
